# Default values for router.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

router:
  router:
    configuration:
      # duplicated in environments/prod.yaml
      health-check:
        listen: 0.0.0.0:8088
      include_subgraph_errors:
        all: true
      plugins:
        experimental.expose_query_plan: true
  ingress:
    enabled: true
  containerPorts:
    http: 80
  serviceAccount:
    create: false
    name: secrets-csi-k8s
  service:
    annotations:
      cloud.google.com/backend-config: '{"default": "http-hc-config"}'
  extraVolumeMounts:
    - name: apollo-secrets
      mountPath: "/var/secrets"
      readOnly: true
  extraVolumes:
    - name: apollo-secrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "apollo-secrets"
  extraEnvVars:
    - name: APOLLO_KEY
      valueFrom:
        secretKeyRef:
          name: apollokey
          key: pwd
