{{- if .Values.ingress.enabled -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: http-hc-config
spec:
  healthCheck:
    checkIntervalSec: 15
    port: {{ .Values.healtcheck.port }}
    type: HTTP
    requestPath: /health
{{- end }}
