apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "router.fullname" . }}
  labels: 
    {{- include "router.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    supergraph:
      listen: 0.0.0.0:80
    health-check:
      listen: 0.0.0.0:8088
      enabled: true
    {{- if .Values.monitoring.otel }}
    telemetry:
      tracing:
        otlp: 
          endpoint: http://collector.monitoring:4317
          protocol: grpc
        trace_config:
          service_name: "router"
          service_namespace: "router"
      metrics:
        otlp:
          endpoint: http://collector.monitoring:4317
          protocol: grpc
    {{- end }}
    include_subgraph_errors:
      all: true
    plugins:
      experimental.expose_query_plan: true
