apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "router.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels: 
    {{- include "router.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    supergraph:
      listen: 0.0.0.0:80
    telemetry:
      {{- if .Values.monitoring.otel }}
      tracing:
        otlp: 
          endpoint: http://collector.monitoring:4317
          protocol: grpc
        trace_config:
          service_name: "router"
          service_namespace: "router"
      {{- end }}
      metrics:
        prometheus:
          enabled: true
    include_subgraph_errors:
      all: true
    plugins:
      experimental.expose_query_plan: true
