apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: apollo-secrets
spec:
  provider: gcp
  secretObjects:
    - secretName: apollokey
      type: Opaque
      data:
        - objectName: apollo_key.txt
          key: pwd
  parameters:
    secrets: |
      - resourceName: {{ .Values.apolloKeySecretResourceName }}
        fileName: "apollo_key.txt"
