apiVersion: v1
kind: Service
metadata:
  name: {{ include "router.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "router.labels" . | nindent 4 }}
  annotations:
    {{ .Values.service.annotations | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "router.selectorLabels" . | nindent 4 }}
