apiVersion: v1
kind: Service
metadata:
  name: {{ include "router.fullname" . }}
  labels:
    {{- include "router.labels" . | nindent 4 }}
  {{- if .Values.ingress.enabled -}}
  annotations:
    cloud.google.com/backend-config: '{"default": "http-hc-config"}'
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "router.selectorLabels" . | nindent 4 }}
