name: Uninstall Router

# REQUIRED REPO SECRETS
#   - GCP_CREDENTIALS
#   - CLUSTER_PREFIX

on:
  workflow_dispatch:

jobs:
  determine_cloud_provider:
    uses: ./.github/workflows/_determine-provider.yaml
    secrets: inherit

  deploy_gcp:
    if: needs.determine_cloud_provider.outputs.gcp == 'true'
    needs: [determine_cloud_provider]
    uses: ./.github/workflows/_uninstall-router-gke.yaml
    secrets: inherit

  deploy_aws:
    if: needs.determine_cloud_provider.outputs.aws == 'true'
    needs: [determine_cloud_provider]
    uses: ./.github/workflows/_uninstall-router-aws.yaml
    secrets: inherit
